apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: docker.io/postgres:latest
        env:
          - name: POSTGRES_DB
            value: todo_list
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: admin1234
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes: 
      - name: postgres-data
        persistentVolumeClaim:
          claimName: local-pvc